- pipeline.id: catalogue-pipeline
  path.config: '/usr/share/logstash/pipeline/catalogue.conf'

- pipeline.id: catalogue-attr-pipeline
  path.config: '/usr/share/logstash/pipeline/catalogue-attr.conf'
